src/Entity/Detail.php
<?php

namespace App\Entity;
use ApiPlatform\Metadata\ApiResource;
use App\Repository\DetailRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Groups;


#[ORM\Entity(repositoryClass: DetailRepository::class)]
#[ApiResource()]
class Detail
{
    // #[ORM\Id]
    // #[ORM\GeneratedValue]
    // #[ORM\Column]
    // private ?int $id = null;


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['commande:lecture'])]
    private ?int $id=null;

    #[ORM\ManyToOne(inversedBy: 'details')]
    private ?Commande $Commande = null;

    #[ORM\ManyToOne(inversedBy:'details')]
    #[Groups(['commande:lecture'])]
    private ?Produit $Produit = null;

    #[ORM\Column]
    #[Groups(['commande:lecture'])]
    private ?int $quantiteCommandee = null;

    #[ORM\Column(length: 5, nullable: true)]
    private ?string $reduction = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $prixHTDateCom = null;

    public function getId(): ?int
    {
         return $this->id;
    }

    public function getCommande(): ?Commande
    {
        return $this->Commande;
    }

    public function setCommande(?Commande $Commande): static
    {
        $this->Commande = $Commande;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->Produit;
    }

    public function setProduit(?Produit $Produit): static
    {
        $this->Produit = $Produit;

        return $this;
    }

    public function getQuantiteCommandee(): ?int
    {
        return $this->quantiteCommandee;
    }

    public function setQuantiteCommandee(int $quantiteCommandee): static
    {
        $this->quantiteCommandee = $quantiteCommandee;

        return $this;
    }

    public function getReduction(): ?string
    {
        return $this->reduction;
    }

    public function setReduction(?string $reduction): static
    {
        $this->reduction = $reduction;

        return $this;
    }

    public function getPrixHTDateCom(): ?string
    {
        return $this->prixHTDateCom;
    }

    public function setPrixHTDateCom(string $prixHTDateCom): static
    {
        $this->prixHTDateCom = $prixHTDateCom;

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify; //transformer une chaîne de caractères en Slug.
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
#[ORM\Entity(repositoryClass: ProduitRepository::class)]
#[Vich\Uploadable]
#[ApiResource()]
class Produit 
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(/*['produit.index'],*/['commande:lecture'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(/*['produit.index'],*/['commande:lecture'])]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['produit.index'])]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix_HT = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[Vich\UploadableField(mapping: 'products', fileNameProperty:'image')]
    #[Assert\Image()]
    private ?File $imageFile = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    //#[Groups(['produit.show'])]
    private ?SousRubrique $sousRubrique = null;

    /**
     * @var Collection<int, Details>
     */
    #[ORM\OneToMany(mappedBy:'Produit', targetEntity:Detail::class)]
    private Collection $details;

    
    public function __construct1()
    {
        $this->details = new ArrayCollection();
    }

    /**
     * @var Collection<int, Fournit>
     */
    #[ORM\OneToMany(targetEntity: Fournit::class, mappedBy: 'produit', cascade:['remove'])]
    private Collection $fournisseurs;

    #[ORM\ManyToOne(inversedBy: 'product')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Fournisseur $Fournisseur = null;

    /**
     * @var Collection<int, DetailLivraison>
     */
    #[ORM\OneToMany(targetEntity: DetailLivraison::class, mappedBy: 'Produit', orphanRemoval: true)]
    private Collection $detailLivraisons;


    public function __construct()
    {
        //$this->Fournisseur = new Fournisseur();
        $this->fournisseurs = new ArrayCollection();
        $this->detailLivraisons = new ArrayCollection();
        
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixHT(): ?float
    {
        return $this->prix_HT;
    }

    public function setPrixHT(float $prix_HT): static
    {
        $this->prix_HT = $prix_HT;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->prix_HT, 0 ,'',' '); //Tuto graphicart, ça renvoie une chaîne de caractère pour une plus belle mise en page.
    }
    public function getSlug(): string 
    {
        return $slugify = (new Slugify())->slugify($this->nom);
    }

    public function getSousRubrique(): ?SousRubrique
    {
        return $this->sousRubrique;
    }

    public function setSousRubrique(?SousRubrique $sousRubrique): static
    {
        $this->sousRubrique = $sousRubrique;

        return $this;
    }
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }
    public function setImageFile(?File $imageFile): static
    {
        $this->imageFile = $imageFile;
        
        return $this;
    }

    /**
     * @return Collection<int, Fournit>
     */
    public function getFournisseurs(): Collection
    {
        return $this->fournisseurs;
    }

    public function addFournisseur(Fournit $fournisseur): static
    {
        if (!$this->fournisseurs->contains($fournisseur)) {
            $this->fournisseurs->add($fournisseur);
            $fournisseur->setProduit($this);
        }

        return $this;
    }

    public function removeFournisseur(Fournit $fournisseur): static
    {
        if ($this->fournisseurs->removeElement($fournisseur)) {
            // set the owning side to null (unless already changed)
            if ($fournisseur->getProduit() === $this) {
                $fournisseur->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Detail>
     */

    public function getDetails(): Collection
    {
        return $this->details;
    }

    public function getFournisseur(): ?Fournisseur
    {
        return $this->Fournisseur;
    }

    public function setFournisseur(?Fournisseur $Fournisseur): static
    {
        $this->Fournisseur = $Fournisseur;

        return $this;
    }

    /**
     * @return Collection<int, DetailLivraison>
     */
    public function getDetailLivraisons(): Collection
    {
        return $this->detailLivraisons;
    }

    public function addDetailLivraison(DetailLivraison $detailLivraison): static
    {
        if (!$this->detailLivraisons->contains($detailLivraison)) {
            $this->detailLivraisons->add($detailLivraison);
            $detailLivraison->setProduit($this);
        }

        return $this;
    }

    public function removeDetailLivraison(DetailLivraison $detailLivraison): static
    {
        if ($this->detailLivraisons->removeElement($detailLivraison)) {
            // set the owning side to null (unless already changed)
            if ($detailLivraison->getProduit() === $this) {
                $detailLivraison->setProduit(null);
            }
        }

        return $this;
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Produit;
use App\Repository\ProduitRepository;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/panier', name: 'app_panier')]
class PanierController extends AbstractController
{
    private $userRepo;

    public function __construct(UserRepository $userRepo){
        $this->userRepo = $userRepo;
    }


    #[Route('/', name:'_index')]
    public function index(SessionInterface $session, ProduitRepository $produitRepo)
    {
        $reduction = 1;
        $coefficient = 1;
        if($this->getUser()!=null)
        {
            $identifiant = $this->getUser()->getUserIdentifier();
        if($identifiant){
            $info = $this->userRepo->findOneBy(["email" =>$identifiant]);

                $reduction = $info->getReduction();
                $coefficient = $info->getCoefficient();
        }
        }
        $panier = $session->get('panier', []);
        $data = [];
        $total =0;
        
        foreach($panier as $id => $quantite){
           $produit = $produitRepo->find($id);
        
        $data[] = [
            'produit' => $produit,
            'quantite' => $quantite
        ];
        $total += $produit->getPrixHT() * $quantite;
        }
    if (isset($reduction))
    {

     return $this->render('panier/index.html.twig', ['data' => $data, 'total' => $total, 'reduction' => $reduction, 'coefficient' => $coefficient ]);
    }else
    {
        return $this->render('panier/index.html.twig', compact('data', 'total'));
    }
    }
    #[Route('/ajout/{id}', name: '_ajout')]
    public function ajout(Produit $produit,SessionInterface $session)
    {     
    $id = $produit->getId();
    $panier = $session->get('panier', []);

    if(empty($panier[$id])){
        $panier[$id]=$_REQUEST['quantite'];
    }else{
        if(isset($_REQUEST['quantite']))
        {
         $panier[$id]+=$_REQUEST['quantite'];
        }else{

   
        $panier[$id]++;
        }
    }
     $session->set('panier', $panier);
     return $this->redirectToRoute('app_panier_index');
    }
    #[Route('/enlever/{id}', name: '_enlever')]
    public function enlever(Produit $produit,SessionInterface $session)
    {
     
    $id = $produit->getId();

    $panier = $session->get('panier', []);

    if(!empty($panier[$id])){
        if($panier[$id]>1){
        $panier[$id]--;
    }else{
        unset($panier[$id]);
    }
    }
     $session->set('panier', $panier);
     return $this->redirectToRoute('app_panier_index');
    }
    #[Route('/supprimer/{id}', name: '_supprimer')]
    public function supprimer(Produit $produit,SessionInterface $session)
    {
     
    $id = $produit->getId();

    $panier = $session->get('panier', []);

    if(!empty($panier[$id])){
        unset($panier[$id]);
    }
     $session->set('panier', $panier);
     return $this->redirectToRoute('app_panier_index');
    }
    #[Route('/vider', name: '_vider')]
    public function vider(SessionInterface $session)
    {
        $session->remove('panier');
        return $this->redirectToRoute('app_panier_index');
    }
}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre panier{% endblock %}

{% block body %}
<div class="container">
    <section class="row">
        <div class="col-12">
            <h1>Panier</h1>
            <table class="table table-primary">
                <thead>
                    <tr>
                        <th>Produit</th>
                        <th>Prix</th>
                        <th>Quantite</th>
                        <th>Total</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody> 
                        {% for element in data %}
                            <tr>
                                <td>{{ element.produit.nom}}</td>
                                <td>{{ element.produit.prixHT}} €</td>
                                <td>{{element.quantite}}</td>
                                <td>{{element.quantite * element.produit.prixHT}} €</td>
                                <td>
                                <a href="{{ path('app_panier_ajout', {id: element.produit.id})}}" class="btn btn-success">+</a>
                                <a href="{{ path('app_panier_enlever',{id: element.produit.id})}}" class="btn btn-warning">-</a>
                                <a href="{{ path('app_panier_supprimer',{id: element.produit.id})}}" class="btn btn-danger">Supprimer</a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="5">Votre panier est vide</td>
                            </tr>
                        {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3">Total HT</td>
                        <td colspan="2">{{ total }} €</td>
                    </tr>
                    <tr>
                        <td colspan="3">Total TTC</td>
                        <td>{{total * 1.20}} €</td>
                        <td>
                            {% if reduction == 1 and coefficient == 1 %}
                            <a href="{{ path('app_panier_vider')}}" class="btn btn-danger">Vider</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% if reduction != 1 and coefficient != 1  %}
                    <tr>
                    <td colspan="3">Total TTC avec reduction de {{ 100 - (reduction * 100) }} % et coefficient de réduction {{ 100 - (coefficient * 100) }} % </td>
                    <td> {{total * 1.20 * reduction * coefficient }} € </td>
                    <td>  <a href="{{ path('app_panier_vider')}}" class="btn btn-danger">Vider</a> </td>
                    </tr>
                    {% elseif reduction == 1 and coefficient != 1  %}
                    <tr>
                    <td colspan="3">Total TTC avec coefficient de réduction {{ 100 - (coefficient * 100) }} % </td>
                    <td> {{total * 1.20 * coefficient }} € </td>
                    <td>  <a href="{{ path('app_panier_vider')}}" class="btn btn-danger">Vider</a> </td>
                    </tr>
                    {% elseif coefficient == 1 and reduction != 1  %}
                    <tr>
                    <td colspan="3">Total TTC avec réduction {{ 100 - (reduction * 100) }} % </td>
                    <td> {{total * 1.20 * reduction }} € </td>
                    <td>  <a href="{{ path('app_panier_vider')}}" class="btn btn-danger">Vider</a> </td>
                    </tr>
                    {% endif %}
                </tfoot>
            </table>
         <a href="{{ path('home')}}" class="btn btn-success">Parcourir les produits</a> 
         <a href="{{ path('app_commande')}}" class="btn btn-primary">Valider la commande</a>
        </div>
    </section>
</div>
{% endblock %}