src/Entity/Livraison.php
<?php

namespace App\Entity;

use App\Repository\LivraisonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivraisonRepository::class)]
class Livraison
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'livraisons')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Commande $Commande = null;

    #[ORM\Column(length: 50)]
    private ?string $Nom = null;

    /**
     * @var Collection<int, DetailLivraison>
     */
    #[ORM\OneToMany(targetEntity: DetailLivraison::class, mappedBy: 'Livraison', orphanRemoval: true)]
    private Collection $detailLivraisons;

    public function __construct()
    {
        $this->detailLivraisons = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommande(): ?Commande
    {
        return $this->Commande;
    }

    public function setCommande(?Commande $Commande): static
    {
        $this->Commande = $Commande;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    /**
     * @return Collection<int, DetailLivraison>
     */
    public function getDetailLivraisons(): Collection
    {
        return $this->detailLivraisons;
    }

    public function addDetailLivraison(DetailLivraison $detailLivraison): static
    {
        if (!$this->detailLivraisons->contains($detailLivraison)) {
            $this->detailLivraisons->add($detailLivraison);
            $detailLivraison->setLivraison($this);
        }

        return $this;
    }

    public function removeDetailLivraison(DetailLivraison $detailLivraison): static
    {
        if ($this->detailLivraisons->removeElement($detailLivraison)) {
            // set the owning side to null (unless already changed)
            if ($detailLivraison->getLivraison() === $this) {
                $detailLivraison->setLivraison(null);
            }
        }

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\CoefficientType;
use App\Form\ModifyUserProType;
use App\Form\ModifyUserType;
use App\Form\ReductionType;
use App\Repository\CommandeRepository;
use App\Repository\UserRepository;
use App\Repository\UtilisateurRepository;
use App\Security\HistoryVerifier;
use Doctrine\ORM\EntityManagerInterface;
use PharIo\Manifest\Requirement;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/profil', name: 'app_profil_')]
class ProfilController extends AbstractController
{
    private $userRepo;

    public function __construct(UserRepository $userRepo){
        $this->userRepo = $userRepo;
    }
    #[Route('/', name:'index')]
    public function index(Security $security,CommandeRepository $commande): Response
    {
        if($this->getUser()!=null)
        {


        $this->denyAccessUnlessGranted('ROLE_USER');
        $identifiant = $this->getUser()->getUserIdentifier(); //-- ICI on récupère l'identifiant unique de l'utilisateur connecté 
        if($identifiant){
            $info = $this->userRepo->findOneBy(["email" =>$identifiant]); //<--- ICI on vérifie qu'on a bien un utilisateur dans la base de donnée qui a ce mail 
            $commandes=$commande->findByUser2($info->getId());

        }
        
        return $this->render('profil/index.html.twig', [
            'informations' => $info,
            'commandes' => $commandes

        ]);
        }else{
            $this->addFlash('warning','Vous devez être authentifié pour accéder à cette page.');
            return $this->redirectToRoute('app_login');
        }
    }

    #[Route('/edit/{id}', name:'edit', requirements:['id' => Requirement::DIGITS])]
    public function edit(User $user, EntityManagerInterface $em,Request $request,)
    {
     $this->denyAccessUnlessGranted('ROLE_EMPLOYE');
     $identifiant = $this->getUser()->getUserIdentifier();
     $info = $this->userRepo->findOneBy(["email" =>$identifiant]);
     $Verif=false;
     
     //dd(intval(substr($_SERVER['REQUEST_URI'],13,strlen($_SERVER['REQUEST_URI']))));
     foreach($info->getEmploye() as $Client)
     {
      if ($Client->getId() == intval(substr($_SERVER['REQUEST_URI'],13,strlen($_SERVER['REQUEST_URI']))))
      {
        $Verif = true;
      }
     }
     if ($Verif == false)
     {
        $this->addFlash('warning', 'Cet utilisateur n\'est pas un de vos clients, vous allez être redirigé à l\'accueil du profil');
        return $this->redirectToRoute('app_profil_index');
     }
     else if ($Verif == true)
     {
     $form = $this->createForm(ReductionType::class, $user);
     $form->handleRequest($request);
     if ($form->isSubmitted() && $form->isValid())
     {
         if($form->getData()->getReduction()<= 0 || ($form->getData()->getReduction()) >=1)
         {
            $this->addFlash('warning', 'La réduction ne peut pas être inférieure à 0 ou supérieure à 1.');
            return $this->redirectToRoute('app_profil_index');
         }
         $em->flush();
         $this->addFlash('succees', 'La réduction a bien été appliquée');
         return $this->redirectToRoute('app_profil_index');
     }
     return $this->render('/profil/edit.html.twig', [
         'user' => $user,
         'form' => $form
     ]);
    }
}
    #[Route('/edit-coef/{id}', name:'edit-coef', requirements:['id' => Requirement::DIGITS])]
    public function edit_coef(User $user, EntityManagerInterface $em,Request $request)
    {
     $this->denyAccessUnlessGranted('ROLE_EMPLOYE');
     $identifiant = $this->getUser()->getUserIdentifier();
     $info = $this->userRepo->findOneBy(["email" =>$identifiant]);
     $Verif=false;
     
     //dd(intval(substr($_SERVER['REQUEST_URI'],13,strlen($_SERVER['REQUEST_URI']))));
     foreach($info->getEmploye() as $Client)
     {
      if ($Client->getId() == intval(substr($_SERVER['REQUEST_URI'],18,strlen($_SERVER['REQUEST_URI']))))
      {
        $Verif = true;
      }
     }
     if ($Verif == false)
     {
        $this->addFlash('warning', 'Cet utilisateur n\'est pas un de vos clients, vous allez être redirigé à l\'accueil du profil');
        return $this->redirectToRoute('app_profil_index');
     } else if ($Verif == true)
     {
     $form = $this->createForm(CoefficientType::class, $user);
     $form->handleRequest($request);
     if ($form->isSubmitted() && $form->isValid())
     {
         if($form->getData()->getCoefficient()<= 0 || ($form->getData()->getCoefficient()) >=1)
         {
            $this->addFlash('warning', 'Le coefficient ne peut pas être inférieure à 0 ou supérieure à 1.');
            return $this->redirectToRoute('app_profil_index');
         }
         $em->flush();
         $this->addFlash('succees', 'Le coefficient a bien été modifié');
         return $this->redirectToRoute('app_profil_index');
     }
     return $this->render('/profil/edit.html.twig', [
         'user' => $user,
         'form' => $form
     ]);
    }
    }
    #[Route('/modify/{id}', name:'modify', requirements:['id' => Requirement::DIGITS])]
    public function modify(User $user, EntityManagerInterface $em, Request $request, UserPasswordHasherInterface $userPasswordHasher)
    {
        if($this->getUser()!=$user)
        {
         $this->addFlash('danger','TU N\'AS PAS LE DROIT DE FAIRE CA.');
         return $this->redirectToRoute('app_profil_index');
        }
        $form = $this->createForm(ModifyUserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            $em->flush();
            $this->addFlash('succees', 'Vos coordonnées ont bien été modifiées');
            return $this->redirectToRoute('app_profil_index');
        }
        return $this->render('/profil/modify.html.twig', [
            'user' => $user,
            'form' => $form
        ]);
    }
    #[Route('/modifypro/{id}', name:'modifypro', requirements:['id' => Requirement::DIGITS])]
    public function modifyPro(User $user, EntityManagerInterface $em, Request $request, UserPasswordHasherInterface $userPasswordHasher)
    {
        $this->denyAccessUnlessGranted('ROLE_CLIENT_PROFESSIONNEL');
        if($this->getUser()!=$user)
        {
         $this->addFlash('danger','TU N\'AS PAS LE DROIT DE FAIRE CA.');
         return $this->redirectToRoute('app_profil_index');
        }
        $form = $this->createForm(ModifyUserProType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            $em->flush();
            $this->addFlash('succees', 'Vos coordonnées ont bien été modifiées');
            return $this->redirectToRoute('app_profil_index');
        }
        return $this->render('/profil/modify.html.twig', [
            'user' => $user,
            'form' => $form
        ]);
    }
}

templates/profil/edit.html.twig
{% extends 'base.html.twig' %}
 {% block title "Client : " ~  user.nom %}
{% block body %}
<div class="container">
    {{form_start(form)}}
    
    {{form_end(form)}}
</div>
 {% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-sm-8 offset-sm-2">
                <h1>Vos informations</h1>
                <table class="table table-light table-hover">
                    <thead>
                    <tr>
                        <th>Email</th>
                        <th>Rôles</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{{ informations.email }}</td>
            {#                        Les rôles sont un tableau, il nous faire une boucle :#}
                        <td>
                        {% for role in informations.roles %}
                        {{ role }} 
                        {% endfor %}
                        </td>
                        <td>{% if is_granted('ROLE_CLIENT_PROFESSIONNEL') %}
                        <a href="{{path('app_profil_modifypro',{id:informations.id})}}">Modifier vos coordonnées</a>
                            {% else %}
                        <a href="{{path('app_profil_modify',{id:informations.id})}}">Modifier vos coordonnées</a>
                        {% endif %}
                        </td>
                    </tr>
                    </tbody>
                </table>
            {% if informations.reduction != 1 %}
            <div class="row">
            <p>Vous bénéficiez d'une réduction de {{100-(informations.reduction  * 100 )}} % sur votre prochaine commande. </p>
            </div>
            {% endif %}
            {% if informations.coefficient != 1 %}
            <div class="row">
            <p>Vous bénéficiez d'une réduction de {{100-(informations.coefficient * 100)}} % sur toutes les commandes que vous faites.</p>
            </div>
            {% endif %}
        {% for commande in commandes %}
        
        <div class="row"><p>Commande du {{commande.dateCommande | date('d/m/y')}}#{{commande.id}}</p>
        <table class="table table-light table-hover table-striped">
            <thead>
                <tr>
                    <th>Nom du produit</th>
                    <th>Quantité commandée</th>
                    <th>Prix total du produit</th>

                </tr>
                </thead>
                <tbody>
                <tr>
            {% for detail in commande.details %}
                    <td>{{ detail.produit.nom }}</td>
                    <td>{{ detail.quantiteCommandee }}</td>
                    <td>{{ detail.prixHTDateCom * commande.coefficient * commande.valeurReduction }} €</td>
                </tr>
                <tr>
                <td>{{detail.produit.nom}} x {{ detail.quantiteCommandee }}</td>
                <td> = </td>
                <td>{{detail.prixHTDateCom * commande.coefficient * commande.valeurReduction * detail.quantiteCommandee}} € HT</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
                    <tr>
                        <td colspan="2">Total (TVA 20%) </td>
                        <td>{{ commande.montantCommandeTTC }} €</td>
                    </tr>
                     <tr>
                        <td colspan="3">Facturé au {{commande.adresseFacturation}}, {{commande.villeFacturation}}</td>                  
                    </tr>
                    <tr>
                        <td colspan="2">Livré au {{commande.adresseLivraison}}, {{commande.villeLivraison}}</td>
                        <td>Livré le {{commande.getLivraisons[0].getDetailLivraisons[0].getDateLivraison| date('d/m/y')}}</td>                  
                    </tr>
            </tfoot>
            </table>
           
            </div>
            {% endfor %}
             {% if is_granted('ROLE_EMPLOYE') %}

        <div class="row"><h2>Vos clients à charge</h2>
        {% for client in informations.Employe %}
        
        <div class="row">
        <table class="table table-light table-hover table-striped">
            <thead>
                <tr>
                    <th>Nom et prénom du client</th>
                    <th>Email</th>
                    <th>Action : prochaine commande</th>
                    <th>Action : réduction permanente</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ client.nom}} {{ client.prenom }}</td>
                    <td>{{ client.email }}</td>
                    <td>
                        {% if client.reduction == 1 %}
                        <a class="btn btn-success btn-sm" href="{{ path('app_profil_edit', { id: client.id }) }}">Appliquer une réduction</a>
                        {% else %}
                         <a class="btn btn-success btn-sm disabled" href="{{ path('app_profil_edit', { id: client.id }) }}">Réduction appliquée</a>
                        {% endif %}
                    </td>
                    <td>
                        <a class="btn btn-success btn-sm" href="{{ path('app_profil_edit-coef', { id: client.id }) }}">Changer le coefficient</a>
                    </td>
                </tr>
            </tbody>
            </table>
            </div>
            {% endfor %}
            </div>

            <div class="row">
            <a class="btn btn-success btn-sm" href="/profil/requete">Consulter les requêtes de vos clients</a>
            </div>
            {% endif %}

            {# {{informations.employeCharge.email}} #}
            {% if informations.employeCharge.email is defined %}
    <div class="row">
            <a class="btn btn-success btn-sm" href="/profil/requete/">Soumettre une requête au commercial encadrant.</a>
    </div>
            {% endif %}
</div>
</div>
{% endblock %}

templates/profil/modify.html.twig
{% extends 'base.html.twig' %}
 {% block title "Modifiez vos coordonnées" %}
{% block body %}
<div class="container">
    {{form_start(form)}}
    
    {{form_end(form)}}
</div>
 {% endblock %}