src/Entity/Produit.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify; //transformer une chaîne de caractères en Slug.
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
#[ORM\Entity(repositoryClass: ProduitRepository::class)]
#[Vich\Uploadable]
#[ApiResource()]
class Produit 
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(/*['produit.index'],*/['commande:lecture'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(/*['produit.index'],*/['commande:lecture'])]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['produit.index'])]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix_HT = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[Vich\UploadableField(mapping: 'products', fileNameProperty:'image')]
    #[Assert\Image()]
    private ?File $imageFile = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    //#[Groups(['produit.show'])]
    private ?SousRubrique $sousRubrique = null;

    /**
     * @var Collection<int, Details>
     */
    #[ORM\OneToMany(mappedBy:'Produit', targetEntity:Detail::class)]
    private Collection $details;

    
    public function __construct1()
    {
        $this->details = new ArrayCollection();
    }

    /**
     * @var Collection<int, Fournit>
     */
    #[ORM\OneToMany(targetEntity: Fournit::class, mappedBy: 'produit', cascade:['remove'])]
    private Collection $fournisseurs;

    #[ORM\ManyToOne(inversedBy: 'product')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Fournisseur $Fournisseur = null;

    /**
     * @var Collection<int, DetailLivraison>
     */
    #[ORM\OneToMany(targetEntity: DetailLivraison::class, mappedBy: 'Produit', orphanRemoval: true)]
    private Collection $detailLivraisons;


    public function __construct()
    {
        //$this->Fournisseur = new Fournisseur();
        $this->fournisseurs = new ArrayCollection();
        $this->detailLivraisons = new ArrayCollection();
        
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixHT(): ?float
    {
        return $this->prix_HT;
    }

    public function setPrixHT(float $prix_HT): static
    {
        $this->prix_HT = $prix_HT;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->prix_HT, 0 ,'',' '); //Tuto graphicart, ça renvoie une chaîne de caractère pour une plus belle mise en page.
    }
    public function getSlug(): string 
    {
        return $slugify = (new Slugify())->slugify($this->nom);
    }

    public function getSousRubrique(): ?SousRubrique
    {
        return $this->sousRubrique;
    }

    public function setSousRubrique(?SousRubrique $sousRubrique): static
    {
        $this->sousRubrique = $sousRubrique;

        return $this;
    }
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }
    public function setImageFile(?File $imageFile): static
    {
        $this->imageFile = $imageFile;
        
        return $this;
    }

    /**
     * @return Collection<int, Fournit>
     */
    public function getFournisseurs(): Collection
    {
        return $this->fournisseurs;
    }

    public function addFournisseur(Fournit $fournisseur): static
    {
        if (!$this->fournisseurs->contains($fournisseur)) {
            $this->fournisseurs->add($fournisseur);
            $fournisseur->setProduit($this);
        }

        return $this;
    }

    public function removeFournisseur(Fournit $fournisseur): static
    {
        if ($this->fournisseurs->removeElement($fournisseur)) {
            // set the owning side to null (unless already changed)
            if ($fournisseur->getProduit() === $this) {
                $fournisseur->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Detail>
     */

    public function getDetails(): Collection
    {
        return $this->details;
    }

    public function getFournisseur(): ?Fournisseur
    {
        return $this->Fournisseur;
    }

    public function setFournisseur(?Fournisseur $Fournisseur): static
    {
        $this->Fournisseur = $Fournisseur;

        return $this;
    }

    /**
     * @return Collection<int, DetailLivraison>
     */
    public function getDetailLivraisons(): Collection
    {
        return $this->detailLivraisons;
    }

    public function addDetailLivraison(DetailLivraison $detailLivraison): static
    {
        if (!$this->detailLivraisons->contains($detailLivraison)) {
            $this->detailLivraisons->add($detailLivraison);
            $detailLivraison->setProduit($this);
        }

        return $this;
    }

    public function removeDetailLivraison(DetailLivraison $detailLivraison): static
    {
        if ($this->detailLivraisons->removeElement($detailLivraison)) {
            // set the owning side to null (unless already changed)
            if ($detailLivraison->getProduit() === $this) {
                $detailLivraison->setProduit(null);
            }
        }

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\SousRubrique;
use App\Entity\Fournisseur;
use App\Entity\Produit;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('prix_HT')
            ->add('image', TextType::class,[
                'disabled' => true,
                'label' => 'nom de l\'image',
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('stock', TextType::class,[
                'disabled' => true,
                'required' => false,
            ])
            ->add('sousRubrique', EntityType::class, [
                'class' => SousRubrique::class,
                'choice_label' => 'nom',
                'required' => false
            ])
            ->add('Fournisseur', EntityType::class, [
                'class' => Fournisseur::class,
                'choice_label' => 'nom',
            ])
            ->add('save',SubmitType::class, [
                'label' => 'Sauvegarder les changements' ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/AApi/ProduitController.php
<?php

namespace App\Controller\AApi;

use App\Entity\Produit;
use App\Repository\ProduitRepository;
use PharIo\Manifest\Requirement;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;



class ProduitController extends AbstractController

{


    #[Route("/aapi/produits")]
    public function index (ProduitRepository $repository)
    {
        $produit = $repository->findAll();
        return $this->json($produit, 200,[],[
            'groups' => ['produit.index','produit.show']
        ]);
         
    }
    #[Route("/aapi/produits/{id}", requirements:['id' => Requirement::DIGITS])]
    public function show(Produit $produit)
    {
        return $this->json($produit, 200,[],[
            'groups' => ['produit.index','produit.show']
        ]);
         
    }
    
    
}

src/Controller/Admin/ProduitController.php
<?php

namespace App\Controller\Admin;
use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\SousRubriqueRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityManagerInterface;
//use Doctrine\Persistence\ObjectManager; Inutile et trop complexe.
//use Doctrine\Bundle\DoctrineBundle\Registry;
//use Doctrine\Persistence\ManagerRegistry as PersistenceManagerRegistry;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\Persistence\ManagerRegistry; //CET ATTRIBUT POUR MODIFIER LES CHAMPS PAS L'OBJECT MANAGER.
use PharIo\Manifest\Requirement;
use Vich\UploaderBundle;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

#[Route("/admin/produit", name: 'app_admin_produit_')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(ProduitRepository $produitRepository, SousRubriqueRepository $sousRubriqueRepository, /*EntityManagerInterface $em*/): Response
    {
        $produits = $produitRepository->findAll();
        return $this->render('admin/produit/index.html.twig', [
            'produits' => $produits
        ]);
    }
    #[Route('/{id}/edit', name: 'edit', requirements: ['id' => Requirement::DIGITS])]
    public function edit(Produit $produit, Request $request, EntityManagerInterface $em)
    {
        //$this->denyAccessUnlessGranted('ROLE_ADMIN');
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $form->getData()->setImage('');
            $em->flush();
            $this->addFlash('success', 'La modification du produit concerné a été enregistrée.');
            return $this->redirectToRoute('app_admin_produit_index');
        }
        return $this->render('admin/produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form
        ]);
    }
    #[Route('/create', name:'create')]
    public function create(Request $request, EntityManagerInterface $em)
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $form->getData()->setStock(0);
            $em->persist($produit);
            $em->flush();
            $this->addFlash('success', 'L\'ajout du produit dans la table a été effectué, n\'hésitez pas a utiliser éditer pour modifier l\'image.');
            return $this->redirectToRoute('app_admin_produit_index');
        }
        return $this->render('admin/produit/create.html.twig' , [
            'form' => $form
        ]);
    }
    #[Route('/{id}', name: 'delete', methods:['DELETE'])]
    public function remove(Produit $produit, EntityManagerInterface $em)
    {
        $em->remove($produit);
        $em->flush();
        $this->addFlash('success', 'Le produit a bien été supprimé');
        return $this->redirectToRoute('app_admin_produit_index');
    }
}

src/Controller/Api/ProduitController.php
<?php

namespace App\Controller\Api;

use App\Entity\Produit;
use App\Repository\ProduitRepository;
use PharIo\Manifest\Requirement;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;



class ProduitController extends AbstractController

{


    #[Route("/api/produits")]
    public function index (ProduitRepository $repository)
    {
        $produit = $repository->findAll();
        return $this->json($produit, 200,[],[
            'groups' => ['produit.index','produit.show']
        ]);
         
    }
    #[Route("/api/produits/{id}", requirements:['id' => Requirement::DIGITS])]
    public function show(Produit $produit)
    {
        return $this->json($produit, 200,[],[
            'groups' => ['produit.index','produit.show']
        ]);
         
    }
    
    
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Repository\ProduitRepository;
use App\Repository\FournitRepository;
use App\Repository\RubriqueRepository;
use App\Repository\SousRubriqueRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ProduitController extends AbstractController
{
    #[Route('/produit', name: 'app_produit')]
    public function index(ProduitRepository $produitRepository,RubriqueRepository $rubriqueRepository, Request $request ): Response
    {
        $sort = $request->query->get('sort', 'popularity'); 
        $produits = $produitRepository->findByFilters($sort);
        $produits2= $produitRepository->findAll();
        $total = count($produits2);
        $rubriques = $rubriqueRepository->findAll();   
        return $this->render('produit/index.html.twig', [
            'controller_name' => 'ProduitController',
            'produits' => $produits,
            'total' => $total,
            'rubriques' => $rubriques

        ]);
    }
    #[Route('/produit/{slug}-{id}', name: 'app_produit_show', requirements: ['slug' => '[a-z0-9\-]*'])]
    public function show(Produit $produit, string $slug,RubriqueRepository $rubriqueRepository)
    {
        //$produit = $this->produitRepository->find($id);
    if ($produit->getSlug() !== $slug)
    {
        return $this->redirectToRoute('app_produit_show', [
            'id' => $produit->getId(),
            'slug' => $produit->getSlug()
        ], 301);
    }
     $rubriques = $rubriqueRepository->findAll();
     return $this->render('produit/show.html.twig' , [
        'produit' => $produit,
        'rubriques' => $rubriques,
        'current_menu' => 'properties'
     ]);
    }
}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
         
<div class="container">
    <h2 class="pt-3">Nos produits</h2>
<div class="btn-group col-auto d-flex">
                <button class="btn btn-sm dropdown-toggle" type="button" id="filterDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <p>Filtre</p>
                </button>
                <ul class="dropdown-menu" aria-labelledby="filterDropdown">
                    <li><a class="dropdown-item" href="{{ path('app_produit', { 'sort': 'price_asc' }) }}">Prix (asc)</a></li>
                    <li><a class="dropdown-item" href="{{ path('app_produit', { 'sort': 'price_desc' }) }}">Prix (desc)</a></li>
                    <li><a class="dropdown-item" href="{{ path('app_produit', { 'sort': 'alphabetical_asc' }) }}">Alphabétique (A-Z)</a></li>
                    <li><a class="dropdown-item" href="{{ path('app_produit', { 'sort': 'alphabetical_desc' }) }}">Alphabétique (Z-A)</a></li>
                    <li><a class="dropdown-item" href="{{ path('app_produit', { 'sort': 'popularity' }) }}">Les plus populaires</a></li>
                </ul>
            </div>
    <div class="row pt-3">
    {% set n = 1 %}
    {% for produit in produits %}
    {% if total % 3 == 2 %}
    {% if (total - n) == 1 or (total - n) == 0 %}
    <div class="row pt-3 d-lg-none">
    </div>
    <div class ="col-lg-1"></div>
        <div class="col-lg-5 card bg-white">
        <div class="card-body">
        <div class="row"><img src="/images/produits/{{produit.image}}" alt="Product_image">
        </div>
        <div class="row">
            <h5 class="card-title">
                <a href="{{ path('app_produit_show', {id: produit.id, slug: produit.slug}) }}">{{produit.nom}}</a>
            </h5>
        <p class="card-text text-dark">{{produit.description}}</p>
        <div class="text-primary" style="font-weight: bold; font-size: 2rem;">{{produit.formattedPrice}} € </div>
        </div>
    </div>
    </div>
    {% else %}
        <div class="row pt-3 d-lg-none">
        </div>
        <div class ="col-lg-1 pt-lg-3"></div>
        <div class="col-lg-3 card bg-white">
        <div class="card-body">
        <div class="row"><img src="/images/produits/{{produit.image}}" alt="Product_image">
        </div>
        <div class="row">
            <h5 class="card-title">
                <a href="{{ path('app_produit_show', {id: produit.id, slug: produit.slug}) }}">{{produit.nom}}</a>
            </h5>
        <p class="card-text text-dark">{{produit.description}}</p>
        <div class="text-primary" style="font-weight: bold; font-size: 2rem;">{{produit.formattedPrice}} € </div>
        </div>
    </div>
    </div>
    {% endif %}
    {% endif %}
    {% if total % 3 == 1 %}
    {% if (total - n) == 0 %}
        <div class="row pt-3 d-lg-none">
        </div>
        <div class ="col-lg-2 pt-lg-3"></div>
        <div class="col-lg-9 card bg-white">
        <div class="card-body">
        <div class="row"><img src="/images/produits/{{produit.image}}" alt="Product_image">
        </div>
        <div class="row">
            <h5 class="card-title">
                <a href="{{ path('app_produit_show', {id: produit.id, slug: produit.slug}) }}">{{produit.nom}}</a>
            </h5>
        <p class="card-text text-dark">{{produit.description}}</p>
        <div class="text-primary" style="font-weight: bold; font-size: 2rem;">{{produit.formattedPrice}} € </div>
        </div>
    </div>
    </div>
    <div class="col-lg-1"></div>
    {% else %}
        <div class="row pt-3 d-lg-none">
        </div>
        <div class ="col-lg-1 pt-lg-3"></div>
        <div class="col-lg-3 card bg-white">
        <div class="card-body">
        <div class="row"><img src="/images/produits/{{produit.image}}" alt="Product_image">
        </div>
        <div class="row">
            <h5 class="card-title">
                <a href="{{ path('app_produit_show', {id: produit.id, slug: produit.slug}) }}">{{produit.nom}}</a>
            </h5>
        <p class="card-text text-dark">{{produit.description}}</p>
        <div class="text-primary" style="font-weight: bold; font-size: 2rem;">{{produit.formattedPrice}} € </div>
        </div>
    </div>
    </div>
    {% endif %}
    {% endif %}
    {% if total % 3 == 0 %}
        <div class="row pt-3 d-lg-none">
        </div>
        <div class ="col-lg-1 pt-lg-3"></div>
        <div class="col-lg-3 card bg-white">
        <div class="card-body">
        <div class="row"><img src="/images/produits/{{produit.image}}" alt="Product_image">
        </div>
        <div class="row">
            <h5 class="card-title">
                <a href="{{ path('app_produit_show', {id: produit.id, slug: produit.slug}) }}">{{produit.nom}}</a>
            </h5>
        <p class="card-text text-dark">{{produit.description}}</p>
        <div class="text-primary" style="font-weight: bold; font-size: 2rem;">{{produit.formattedPrice}} € </div>
        </div>
    </div>
    </div>
    {% endif %}
    {% if n % 3 == 0 %}
    </div>
    <div class="row pt-3 ">
    {% endif %}
    {% set n = n + 1 %}
    {% endfor %}
    </div>
{% endblock %}
        {% block javascripts %}{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}
{% block title "Produit : " ~ produit.nom %} {# Pas besoin de mettre un endblock si ça tient sur une seule ligne #}
{% block body %}

 <div class="container mt-4">
    <div class="card bg-white">
    <div class="card-title d-flex justify-content-center"><p class="desc-title">{{produit.nom}}</p></div>
    <div class="card-body"> 
        <div class="row justify-content-center"><img class="w-50" src="/images/produits/{{produit.image}}" style="align-self:center;" alt="Product_image"></div>
        <div class="col"><div class="d-flex justify-content-center align-center"><p class="d-flex text-center text-dark desc">{{produit.description}}</p></div>
           <div class="text-primary d-flex justify-content-end" style="font-weight: bold; font-size: 2rem;">{{produit.formattedPrice}} € </div>
           {% if produit.stock > 0 %}
                <div class="text-success d-flex justify-content-end" style="font-size: 2rem;">En stock</div>
                {% else %}
                <div class="text-danger d-flex justify-content-end" style="font-size: 2rem;">Hors stock</div>
                {% endif %}
        </div>
    </div>
    </div>   
    <div class="row py-4">
               <form class="d-flex" action="{{ path('app_panier_ajout' , {id: produit.id}) }}" method="post">
               <label for="quantite"></label>
                <select class="form-select" name="quantite" id="quantite">
                <option selected value="1">Choisissez la quantité</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                </select>
                <button type="submit align-self-right" class="btn btn-primary">Acheter</a>
                </div>
   </div>
{% endblock %}